### ISSUE TITLE
environ["COMPUTERNAME"] error -> Linux or MacOS

### ISSUE THREAD

**Issue by Yurri19** [TerrificTable/YouTube-and-TikTok--View-Bot#3]
I was putting the last code and this error appeared:

[=] Encoding PC Name, this might take a few secs
Traceback (most recent call last):
  File "/root/YouTube-and-TikTok--View-Bot/viewbot.py", line 41, in <module>
    VAdeTkgpT = str(os.environ["COMPUTERNAME"].replace("DESKTOP-", ""))
  File "/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'COMPUTERNAME'

**Comment by TerrificTable** [comment]
The Computername thing only works on Windows

**Comment by Yurri19** [comment]
Forgot to ask is it possible for you to remove this function? To run on Linux?

**Comment by Yurri19** [comment]
Could you make one for Linux? I really wanted to test your program

**Comment by TerrificTable** [comment]
> Forgot to ask is it possible for you to remove this function? To run on Linux?

I explained how the bot (and the "uuid" part) works on my <a href="https://terrifictable.github.io/blog/view-bot/#How%20it%20Works">"blog"</a>,  you can just remove the part refrenced in the first codeblock

but i am going to remove the entire "uuid" part soon.... if i dont forget to do it

**Comment by Yurri19** [comment]
'Cause I'll pray for it to happen lol

**Comment by Yurri19** [comment]
hi, i managed to make it work but I didn't understand that sentence :
"Config file path without config.json:"

**Comment by Yurri19** [comment]
Could you explain to me what to do exactly?

**Comment by TerrificTable** [comment]
> Could you explain to me what to do exactly?

Well... you have to put in the path to the folder containing the `config.json` file

**Comment by Yurri19** [comment]
Would you have the script on how to do it? Would help a lot

**Comment by Yurri19** [comment]
In my head it would be easier to run the program, just put the URL and end

**Comment by TerrificTable** [comment]
> In my head it would be easier to run the program, just put the URL and end

I made this some time ago to play arround with selenium and webdriver...

**Comment by TerrificTable** [comment]
and yes it would be easier and i would do it like that now, but i did it diffrentlly when i made this.

**Comment by Yurri19** [comment]
How long would it take you to do that? I don't want to take up too much of your time

**Comment by Yurri19** [comment]
> 
the bot it opens instances at once? like 100 instances at once?

**Comment by TerrificTable** [comment]
> the bot it opens instances at once? like 100 instances at once?

no just one

**Comment by TerrificTable** [comment]
> How long would it take you to do that? I don't want to take up too much of your time

Most of my `"old"` projects are not maintained, like this one, i respond to comments / issues because they get sent to me per email, otherwise i wouldnt know there were any...

So... I will probably never update this repository again
But its open source so you can goahead and do it yourself, thats the reasons my projects are opensource / the reason i use github, i want people to learn how stuff works otherwise i could have made a single executable and put it on mega.nz and share it that way

**Comment by Yurri19** [comment]
But there's nothing to do in that part of the Path?

**Comment by Yurri19** [comment]
I don't think there is a perfect bot, I wanted to improve my knowledge on these subjects, you know? But it's quite exhausting to program, but thanks for your time

**Comment by TerrificTable** [comment]
> I don't think there is a perfect bot, I wanted to improve my knowledge on these subjects, you know? But it's quite exhausting to program, but thanks for your time

thats why i make programms, for others to learn
But yes, depending on what and where you do something its really anoying....

**Comment by Yurri19** [comment]
Would you have an example of how to put the path in the folder that contains the config.json? I searched and didn't find much.

**Comment by TerrificTable** [comment]
/home/terrific/whatever

Folder contains config.json

**Comment by TerrificTable** [comment]
Oh and If you Just Press enter the viewbot will create the config.json File by itself

**Comment by Yurri19** [comment]
Got this error here 
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/YouTube-and-TikTok--View-Bot/viewbot.py", line 280, in <module>
    screen()
  File "/data/data/com.termux/files/home/YouTube-and-TikTok--View-Bot/viewbot.py", line 211, in screen
    get_config()
  File "/data/data/com.termux/files/home/YouTube-and-TikTok--View-Bot/viewbot.py", line 43, in get_config
    with io.open(path, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/terrific/whatever/config.json'

**Comment by TerrificTable** [comment]
if you dont input a config.json file it will create one
